### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ivixq** [tiredofit/docker-mariadb#1]
[ERROR] Can't start server : Bind on unix socket: No such file or directory
2018-01-01 13:33:16 140122613709608 [ERROR] Do you already have another mysqld server running on socket: /run/mysqld/mysqld.sock ?
2018-01-01 13:33:16 140122613709608 [ERROR] Aborting

**Comment by nulled06** [comment]
If anybody get this error, just login to db container and run 
`mkdir /run/mysqld && chown -R mariadb:mariadb /run/mysqld`

**Comment by micha-eleric** [comment]
@nulled06 please explain where and how to login to db container.

**Comment by mikhailkobik** [comment]
I don't think it's actual, but you just need to docker execute in db container and run commands from my post
