### ISSUE TITLE
unable to run backup manually. DB_BACKUP_FREQ not defaulted

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-mariadb#6]
using the current image, I have the same issue that has been reported https://github.com/tiredofit/docker-db-backup/issues/34 

the automatic backup worked, but as the DB_BACKUP_FREQ has not been defaulted and I didn't include it in the environment, I had the error 

`/run: line 171: *60: syntax error: operand expected (error token is "*60")`

**Comment by tiredofit** [comment]
Easy fix - I forgot to reference the new location for storing scripts - I've pushed `tiredofit.mariadb:3.6.2` (and latest) with the fix.

**Comment by joergmschulz** [comment]
Thanks a lot!

```
/assets/functions/00-container: line 357: /tmp/state/$(basename "$PWD"): Is a directory
[INFO] ** [mariadb-backup] Backup Functionality initialized at Thu Sep 17 16:14:54 CEST 2020
[INFO] ** [mariadb-backup] Dumping database: wordpress at Thu Sep 17 16:14:55 CEST 2020
```
This translates to: the backup-now script works, but throws a warning

**Comment by tiredofit** [comment]
Ahh jeez. I'll patch that up shortly as well.

**Comment by tiredofit** [comment]
Tagged as `tiredofit/mariadb:3.6.3` and `latest` - Sorry about that!

**Comment by joergmschulz** [comment]
no reason to be sorry at all - I appreciate your work. Thank you again. All fine now.
